# Generated by Django 4.1.7 on 2023-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_image_alter_book_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='customaddress',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='./static/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.FileField(null=True, upload_to='./static/previews'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author')},
        ),
    ]
